spring.application.name=timecapsule
<<<<<<< HEAD

spring.datasource.url=jdbc:mysql://localhost:3306/timecapsule_db
spring.datasource.username=root
spring.datasource.password=infonet
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.web.resources.cache.period=0
spring.web.resources.chain.cache=false
=======
>>>>>>> fb85a4a (프로젝트 시작)
